---
- name: Setup a windows target
  hosts: all
  become: false
  gather_facts: false
  vars:
    - timezone: GMT Standard Time
    - windows_updates:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
    - packages:
        - git
        - notepadplusplus

  tasks:
    - name: Test connection
      win_ping:

    - name: Set timezone to '{{ timezone }}'
      win_timezone:
        timezone: "{{ timezone }}"

    - name: Reboot a machine that might have lots of updates
      win_reboot:
        reboot_timeout: 3600

    - name: Install all updates without a scheduled task
      win_updates:
        category_names: "{{ windows_updates }}"
        reboot: true

    - name: Install packages
      win_chocolatey:
        name: "{{ packages }}"
        state: present
