---
- name: Exec lookup plugin
  hosts: all
  tasks:
    - name: Retrieve token from plugin
      ansible.builtin.debug:
        msg: "{{ lookup('token') }}"

    - name: Read file from plugin
      ansible.builtin.debug:
        msg: "{{ lookup('fileread', '/etc/hosts') }}"
