---
- name: Ansible Vault sample
  hosts: all
  become: false

  tasks:
    - name: include Ansible Vault
      include_vars: vault.yml

    - name: Print variable
      debug:
        msg: "Print the value of variable {{ fruit }}"
