---
- name: Wait Sample
  hosts: all
  vars:
    wait_minutes: 1

  tasks:

    - name: Pause for {{ wait_minutes | int }} minute(s)
      pause:
        minutes: "{{ wait_minutes | int }}"

    - name: Hello Message
      debug:
        msg: "Hello World!"
