# yamllint disable-file
---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * 3"

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ansible-tower-samples'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible yamllint ansible-lint

      - name: YAML linter.
        run: |
          yamllint .

      - name: ANSIBLE linter.
        run: |
          ansible-lint -vvvv
